# Generated by Django 3.1.7 on 2021-04-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210425_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Us',
            new_name='Contact',
        ),
    ]
