# Generated by Django 3.1.7 on 2021-04-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210501_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
