# Generated by Django 3.1.7 on 2021-05-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210508_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_table',
            old_name='cat1',
            new_name='cat',
        ),
    ]
