# Generated by Django 3.1.7 on 2021-05-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210508_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='cat',
        ),
        migrations.AddField(
            model_name='register_table',
            name='cat1',
            field=models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='cat2',
            field=models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='cat3',
            field=models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], max_length=250, null=True),
        ),
    ]
