# Generated by Django 3.1.7 on 2021-04-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20210421_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='dsc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='creator',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
