# Generated by Django 3.1.7 on 2021-04-21 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator', '0003_auto_20210421_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/images/profile_img.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='creator',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
