# Generated by Django 3.1.7 on 2021-04-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_auto_20210421_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='cat1',
            field=models.CharField(blank=True, default='none', max_length=70),
        ),
        migrations.AlterField(
            model_name='creator',
            name='cat2',
            field=models.CharField(blank=True, default='none', max_length=70),
        ),
        migrations.AlterField(
            model_name='creator',
            name='cat3',
            field=models.CharField(blank=True, default='none', max_length=70),
        ),
        migrations.AlterField(
            model_name='creator',
            name='cat4',
            field=models.CharField(blank=True, default='none', max_length=70),
        ),
        migrations.AlterField(
            model_name='creator',
            name='dsc',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='creator',
            name='email',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='creator',
            name='facebook',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='creator',
            name='first',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='creator',
            name='instagram',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='creator',
            name='last',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='creator',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='creator',
            name='snapchat',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='creator',
            name='youtube',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
