# Generated by Django 3.1.7 on 2021-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210425_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='facebook',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='instagram',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='snapchat',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='youtube',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
