# Generated by Django 3.1.7 on 2021-04-30 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210425_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register_table',
            name='facebook',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='instagram',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='youtube',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
