# Generated by Django 3.1.7 on 2021-05-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210501_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='cat2',
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='cat3',
        ),
        migrations.AlterField(
            model_name='register_table',
            name='cat1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
