# Generated by Django 3.1.7 on 2021-05-20 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_auto_20210509_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d')),
                ('age', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, max_length=250)),
                ('instagram', models.URLField(blank=True, max_length=250)),
                ('facebook', models.URLField(blank=True, max_length=250)),
                ('snapchat', models.URLField(blank=True, max_length=250, null=True)),
                ('cat1', models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], max_length=250, null=True)),
                ('cat2', models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], max_length=250, null=True)),
                ('cat3', models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], max_length=250, null=True)),
                ('job', models.CharField(blank=True, max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='creator',
            name='user',
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='creator',
        ),
    ]
