# Generated by Django 3.1.7 on 2021-06-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_profile_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wing',
        ),
        migrations.AddField(
            model_name='profile',
            name='cat1',
            field=models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cat2',
            field=models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cat3',
            field=models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
