# Generated by Django 3.1.7 on 2021-06-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210624_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact_number',
            new_name='contact',
        ),
    ]
