# Generated by Django 3.1.7 on 2021-07-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210624_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cat1',
            field=models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cat2',
            field=models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cat3',
            field=models.CharField(blank=True, choices=[('1', 'Fashion'), ('2', 'Food'), ('3', 'Music'), ('4', 'Art'), ('5', 'Lifestyle')], default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='image'),
        ),
    ]
